name: Build and Publish Catalog Service

on:
   push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from your GitHub repository
      - name: Checkout
        uses: actions/checkout@v4

    # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
         username: ${{ secrets.DOCKER_HUB_USERNAME }}
         password: ${{ secrets.DOCKER_HUB_PASSWORD }}
 
    # Build the Docker image from the Dockerfile
      - name: Build Docker image
        run: |
         docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/catalog-service:latest -f catalog-service/Dockerfile .
   
    # Push the Docker image to Docker Hub
      - name: Push Docker image
        run: |
         docker push ${{ secrets.DOCKER_HUB_USERNAME }}/catalog-service:latest
      
      
